all:
	g++ -o programming_assignment3 programming_assignment3.cpp

dump:
	objdump -d programming_assignment3 > programming_assignment3.asm

clean:
	rm -f programming_assignment3.o programming_assignment3

run: programming_assignment3
	./programming_assignment3
