all:
	g++ -o Assignment5_question1 Assignment5_question1.cpp

dump:
	objdump -d Assignment5_question1 > Assignment5_question1.asm

clean:
	rm -f Assignment5_question1.o Assignment5_question1

run: Assignment5_question1
	./Assignment5_question1
